import type { Appointment, Therapist, Treatment } from "./types";

export const clinicProfile = {
  name: "FisioNova Clínica",
  tagline: "Fisioterapia cercana para volver a moverte con confianza.",
  address: "Calle Salud 18, Madrid",
  phone: "910 123 456",
  email: "hola@fisionova.demo",
  openingHours: "lunes a viernes, 10:00-19:00",
};

export const treatments: Treatment[] = [
  {
    id: "general",
    name: "Fisioterapia general",
    durationMinutes: 50,
    price: 45,
    description:
      "Dolor muscular, contracturas, movilidad y recuperación funcional.",
  },
  {
    id: "sports",
    name: "Fisioterapia deportiva",
    durationMinutes: 50,
    price: 50,
    description: "Prevención y recuperación de lesiones deportivas.",
  },
  {
    id: "postural",
    name: "Reeducación postural",
    durationMinutes: 60,
    price: 55,
    description: "Trabajo guiado para espalda, cuello y hábitos posturales.",
  },
];

export const therapists: Therapist[] = [
  { id: "marta", name: "Marta Ruiz", specialty: "Fisioterapia deportiva" },
  {
    id: "alvaro",
    name: "Álvaro Marín",
    specialty: "Dolor de espalda y postura",
  },
];

export const availableTimes = [
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
];

export const demoDates = [
  "2026-06-01",
  "2026-06-02",
  "2026-06-03",
  "2026-06-04",
  "2026-06-05",
];

export const seedAppointments: Appointment[] = [
  {
    id: "apt-demo-1",
    patientName: "Laura Gómez",
    patientEmail: "laura@example.com",
    patientPhone: "600 111 222",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-02",
    time: "17:00",
    status: "confirmed",
    notes: "Molestia en rodilla derecha.",
  },
  {
    id: "apt-demo-2",
    patientName: "Carlos Perez",
    patientEmail: "carlos@example.com",
    patientPhone: "611 203 445",
    treatmentId: "general",
    therapistId: "alvaro",
    date: "2026-06-01",
    time: "10:00",
    status: "confirmed",
    notes: "Dolor cervical al trabajar con ordenador.",
  },
  {
    id: "apt-demo-3",
    patientName: "Nuria Martin",
    patientEmail: "nuria@example.com",
    patientPhone: "622 814 009",
    treatmentId: "postural",
    therapistId: "alvaro",
    date: "2026-06-01",
    time: "12:00",
    status: "confirmed",
    notes: "Primera visita para reeducacion postural.",
  },
  {
    id: "apt-demo-4",
    patientName: "Javier Torres",
    patientEmail: "javier@example.com",
    patientPhone: "633 425 718",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-01",
    time: "16:00",
    status: "confirmed",
    notes: "Sobrecarga en gemelo izquierdo.",
  },
  {
    id: "apt-demo-5",
    patientName: "Paula Sanchez",
    patientEmail: "paula@example.com",
    patientPhone: "644 782 111",
    treatmentId: "general",
    therapistId: "marta",
    date: "2026-06-02",
    time: "11:00",
    wantsEarlier: true,
    status: "confirmed",
    notes: "Dolor lumbar recurrente.",
  },
  {
    id: "apt-demo-6",
    patientName: "Miguel Arias",
    patientEmail: "miguel@example.com",
    patientPhone: "655 302 764",
    treatmentId: "postural",
    therapistId: "alvaro",
    date: "2026-06-02",
    time: "16:00",
    status: "awaiting_response",
    notes: "Seguimiento de movilidad toracica.",
  },
  {
    id: "apt-demo-7",
    patientName: "Irene Castro",
    patientEmail: "irene@example.com",
    patientPhone: "666 924 381",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-03",
    time: "10:00",
    status: "confirmed",
    notes: "Revision de tobillo tras carrera.",
  },
  {
    id: "apt-demo-8",
    patientName: "Ruben Vidal",
    patientEmail: "ruben@example.com",
    patientPhone: "677 103 909",
    treatmentId: "general",
    therapistId: "marta",
    date: "2026-06-03",
    time: "12:00",
    status: "confirmed",
    notes: "Contractura dorsal.",
  },
  {
    id: "apt-demo-9",
    patientName: "Elena Bravo",
    patientEmail: "elena@example.com",
    patientPhone: "688 714 520",
    treatmentId: "postural",
    therapistId: "alvaro",
    date: "2026-06-03",
    time: "17:00",
    status: "confirmed",
    notes: "Ejercicio terapeutico y pauta en casa.",
  },
  {
    id: "apt-demo-10",
    patientName: "Sergio Leon",
    patientEmail: "sergio@example.com",
    patientPhone: "699 018 245",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-04",
    time: "11:00",
    wantsEarlier: true,
    status: "confirmed",
    notes: "Readaptacion de rodilla.",
  },
  {
    id: "apt-demo-11",
    patientName: "Marta Diez",
    patientEmail: "marta.diez@example.com",
    patientPhone: "610 423 775",
    treatmentId: "general",
    therapistId: "alvaro",
    date: "2026-06-04",
    time: "16:00",
    status: "confirmed",
    notes: "Dolor de hombro derecho.",
  },
  {
    id: "apt-demo-12",
    patientName: "Andres Molina",
    patientEmail: "andres@example.com",
    patientPhone: "621 884 632",
    treatmentId: "postural",
    therapistId: "alvaro",
    date: "2026-06-04",
    time: "18:00",
    status: "confirmed",
    notes: "Control de postura y respiracion.",
  },
  {
    id: "apt-demo-13",
    patientName: "Clara Nuñez",
    patientEmail: "clara@example.com",
    patientPhone: "632 044 518",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-05",
    time: "10:00",
    status: "confirmed",
    notes: "Descarga previa a competicion.",
  },
  {
    id: "apt-demo-14",
    patientName: "Hector Ramos",
    patientEmail: "hector@example.com",
    patientPhone: "643 512 087",
    treatmentId: "general",
    therapistId: "alvaro",
    date: "2026-06-05",
    time: "12:00",
    status: "confirmed",
    notes: "Sesion de mantenimiento.",
  },
  {
    id: "apt-demo-15",
    patientName: "Silvia Ortega",
    patientEmail: "silvia@example.com",
    patientPhone: "654 810 347",
    treatmentId: "postural",
    therapistId: "alvaro",
    date: "2026-06-05",
    time: "17:00",
    wantsEarlier: true,
    status: "confirmed",
    notes: "Revision de pauta de ejercicios.",
  },
  {
    id: "apt-demo-16",
    patientName: "Diego Marin",
    patientEmail: "diego@example.com",
    patientPhone: "665 903 110",
    treatmentId: "sports",
    therapistId: "marta",
    date: "2026-06-02",
    time: "10:00",
    status: "cancelled",
    notes: "Cancelada por el paciente.",
  },
  {
    id: "apt-demo-17",
    patientName: "Ana Rios",
    patientEmail: "ana@example.com",
    patientPhone: "676 120 984",
    treatmentId: "general",
    therapistId: "alvaro",
    date: "2026-06-03",
    time: "18:00",
    status: "cancelled",
    notes: "Cambio pendiente de confirmar.",
  },
  {
    id: "apt-demo-18",
    patientName: "Bloqueo: reunion de equipo",
    patientEmail: "recepcion@fisionova.demo",
    patientPhone: "-",
    treatmentId: "general",
    therapistId: "marta",
    date: "2026-06-01",
    time: "14:00",
    status: "blocked",
    notes: "Reunion de recepcion y fisios.",
  },
];
